import { Check, Zap, Star, Sparkles, MessageCircle } from 'lucide-react';

export const pricingPlans = {
  starter: {
    name: 'Starter',
    description: 'Untuk warung & cafe baru merintis.',
    price: {
      monthly: 0,
      annual: 0,
    },
    priceLabel: 'Rp 0',
    period: '/bulan',
    subtext: 'Gratis selamanya',
    features: [
      'Unlimited Menu Items',
      'QR Code Generator',
      'Basic Analytics',
      '1 Outlet',
      'Support via Email',
    ],
    detailedFeatures: [
      'Unlimited Menu Items',
      'QR Code Generator',
      'Basic Analytics Dashboard',
      '1 Outlet Location',
      'Email Support (48 jam)',
      'Menu Customization',
      'Basic Reporting',
    ],
    buttonText: 'Mulai Gratis Sekarang',
    buttonVariant: 'default' as const,
    popular: false,
  },
  pro: {
    name: 'Pro Business',
    description: 'Untuk restoran yang ingin scale-up.',
    price: {
      monthly: 99000,
      annual: 79000,
    },
    priceLabel: {
      monthly: 'Rp 99rb',
      annual: 'Rp 79rb',
    },
    period: '/bulan',
    subtext: {
      monthly: null,
      annual: 'Ditagih Rp 948.000 per tahun (Hemat Rp 240rb!)',
    },
    features: [
      'Semua fitur Starter',
      'Custom Domain (nama-resto.com)',
      'Advanced Analytics & Export',
      'Unlimited Outlets',
      'Priority Support 24/7',
      'Hapus Branding Menify',
    ],
    detailedFeatures: [
      'Semua fitur Starter',
      'Custom Domain (nama-resto.com)',
      'Advanced Analytics & Export Data',
      'Unlimited Outlets & Locations',
      'Priority Support 24/7 (WhatsApp)',
      'Hapus Branding Menify',
      'Custom Menu Themes',
      'Inventory Management',
      'Staff Account Management',
      'Advanced Reporting & Insights',
    ],
    buttonText: 'Coba Pro 14 Hari Gratis',
    buttonVariant: 'gradient' as const,
    popular: true,
    icon: Zap,
  },
  enterprise: {
    name: 'Enterprise',
    description: 'Untuk chain restaurant & franchise.',
    price: 'Custom',
    priceLabel: 'Custom',
    period: '',
    subtext: 'Hubungi sales untuk harga khusus',
    features: [
      'Semua fitur Pro',
      'Unlimited Outlets & Staff',
      'White Label Solution',
      'Custom Integration & API',
      'Dedicated Account Manager',
      'SLA 99.9% Uptime',
    ],
    detailedFeatures: [
      'Semua fitur Pro',
      'Unlimited Outlets & Staff Accounts',
      'White Label Solution (Your Brand)',
      'Custom Integration & API Access',
      'Dedicated Account Manager',
      'SLA 99.9% Uptime Guarantee',
      'Custom Feature Development',
      'On-premise Deployment Option',
      'Advanced Security & Compliance',
      'Training & Onboarding Support',
      'Multi-language Support',
      'Custom Reporting & Analytics',
    ],
    buttonText: 'Hubungi Sales',
    buttonVariant: 'outline' as const,
    popular: false,
    icon: Sparkles,
    contactLink: 'https://wa.me/6289654061718?text=Halo,%20saya%20tertarik%20dengan%20paket%20Enterprise%20Menify',
  },
};
